server:
  port: 8086
git:
  username: openlibing@163.com
  password: ENC(ac2sDLzYl/zj9MFEwF7wmZsYjn7V1B5J)
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
