server:
  port: 8086
  name: anti-poisoning
git:
  username: openlibing@163.com
  password: ENC(ebUHNmrtczMIZ9rEqRexodzsFI3fKzjQ)
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus
#        exclude: configprops
#  endpoint:
#    health:
#      show-details: always
#  metrics:
#    tags:
#      application: ${server.name}