server:
  port: 8086
spring:
  data:
    mongodb:
      host: 192.168.0.180
      database: test_ci__dev
      port: 8635
      username: rwuser
      password: mindspore#1234
#      password: ENC(I/jdfB8DCY1ic4K49SKJkBj5hrWGs4Qc)
git:
  username: openlibing@163.com
  password: ENC(ac2sDLzYl/zj9MFEwF7wmZsYjn7V1B5J)
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: softwaresupplychain