server:
  port: 8086
spring:
  data:
#    mongodb:
#      host: 7.220.196.137
#      database: vms_dev
#      port: 8635
#      username: rwuser
#      password: Majun@123456
    mongodb:
      host: 192.168.0.180
      database: vms_dev
      port: 8635
      username: rwuser
      password: openMajun@1234
git:
  username: openlibing@163.com
  password: Jszb2022h1