server:
  port: 8086
spring:
  data:
#    mongodb:
#      host: 7.220.196.137
#      database: vms_dev
#      port: 8635
#      username: rwuser
#      password: Majun@123456
    mongodb:
      host: 192.168.0.180
      database: vms_dev
      port: 8635
      username: rwuser
      password: ENC(I/jdfB8DCY1ic4K49SKJkBj5hrWGs4Qc)
git:
  username: openlibing@163.com
  password: ENC(ac2sDLzYl/zj9MFEwF7wmZsYjn7V1B5J)
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: softwaresupplychain