server:
  port: 8086
  name: anti-poisoning
git:
  username: openlibing@163.com
  password: ENC(ebUHNmrtczMIZ9rEqRexodzsFI3fKzjQ)
gitlab:
  username: openlibing@163.com
  password: ENC(ac2sDLzYl/zj9MFEwF7wmZsYjn7V1B5J)
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
servicecomb:
  service:
    environment: acceptance
  rest:
    address: 0.0.0.0:${server.port}?sslEnabled=false
  config:
    client:
      serverUri: https://cse.cn-south-1.myhuaweicloud.com
      refreshMode: 1
      refresh_interval: 5000
  credentials:
    akskCustomCipher: default
    project: cn-south-1
#management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus
#        exclude: configprops
#  endpoint:
#    health:
#      show-details: always
#  metrics:
#    tags:
#      application: ${server.name}